//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int Id { get; set; }
        public Nullable<int> BookId { get; set; }
        public string userId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> BookQuantity { get; set; }
    
        public virtual book book { get; set; }
        public virtual order order { get; set; }
        public virtual User User { get; set; }
    }
}
