//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon
    {
        public string couponcode { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<int> stock { get; set; }
    }
}
